apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app1
spec:
  type: NodePort
  ports:
    - port: 3300
      name: app1
      nodePort: 32000
  selector:
    app: app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: kadam121212/tektonprivate:3.0
          ports:
          - containerPort: 3300
      imagePullSecrets:
        - name: docker-cred
